INSERT INTO Ingredients VALUES (NULL, 'Ackee');
INSERT INTO Ingredients VALUES (NULL, 'Avocado');
INSERT INTO Ingredients VALUES (NULL, 'Allspice');
INSERT INTO Ingredients VALUES (NULL, 'Almond Extract');
INSERT INTO Ingredients VALUES (NULL, 'Almond Milk');
INSERT INTO Ingredients VALUES (NULL, 'Almonds');
INSERT INTO Ingredients VALUES (NULL, 'Ancho Chillies');
INSERT INTO Ingredients VALUES (NULL, 'Anchovy Fillet');
INSERT INTO Ingredients VALUES (NULL, 'Apple Cider Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'Apples');
INSERT INTO Ingredients VALUES (NULL, 'Apricot');
INSERT INTO Ingredients VALUES (NULL, 'Apricot Jam');
INSERT INTO Ingredients VALUES (NULL, 'Asparagus');
INSERT INTO Ingredients VALUES (NULL, 'Aubergine');
INSERT INTO Ingredients VALUES (NULL, 'Avocado');
INSERT INTO Ingredients VALUES (NULL, 'Baby Aubergine');
INSERT INTO Ingredients VALUES (NULL, 'Baby Plum Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Baby Squid');
INSERT INTO Ingredients VALUES (NULL, 'Bacon');
INSERT INTO Ingredients VALUES (NULL, 'Baguette');
INSERT INTO Ingredients VALUES (NULL, 'Baked Beans');
INSERT INTO Ingredients VALUES (NULL, 'Baking Powder');
INSERT INTO Ingredients VALUES (NULL, 'Balsamic Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'Banana');
INSERT INTO Ingredients VALUES (NULL, 'Barbeque Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Basil');
INSERT INTO Ingredients VALUES (NULL, 'Basil Leaves');
INSERT INTO Ingredients VALUES (NULL, 'Basmati Rice');
INSERT INTO Ingredients VALUES (NULL, 'Bay Leaf');
INSERT INTO Ingredients VALUES (NULL, 'Bay Leaves');
INSERT INTO Ingredients VALUES (NULL, 'Bean Sprouts');
INSERT INTO Ingredients VALUES (NULL, 'Beef');
INSERT INTO Ingredients VALUES (NULL, 'Beef Brisket');
INSERT INTO Ingredients VALUES (NULL, 'Beef Fillet');
INSERT INTO Ingredients VALUES (NULL, 'Beef Gravy');
INSERT INTO Ingredients VALUES (NULL, 'Beef Kidney');
INSERT INTO Ingredients VALUES (NULL, 'Beef Shin');
INSERT INTO Ingredients VALUES (NULL, 'Beef Stock');
INSERT INTO Ingredients VALUES (NULL, 'Beef Stock Concentrate');
INSERT INTO Ingredients VALUES (NULL, 'Beetroot');
INSERT INTO Ingredients VALUES (NULL, 'Bicarbonate Of Soda');
INSERT INTO Ingredients VALUES (NULL, 'Biryani Masala');
INSERT INTO Ingredients VALUES (NULL, 'Black Beans');
INSERT INTO Ingredients VALUES (NULL, 'Blackberries');
INSERT INTO Ingredients VALUES (NULL, 'Black Olives');
INSERT INTO Ingredients VALUES (NULL, 'Black Pepper');
INSERT INTO Ingredients VALUES (NULL, 'Black Pudding');
INSERT INTO Ingredients VALUES (NULL, 'Black Treacle');
INSERT INTO Ingredients VALUES (NULL, 'Blueberries');
INSERT INTO Ingredients VALUES (NULL, 'Blue Food Colouring');
INSERT INTO Ingredients VALUES (NULL, 'Boiling Water');
INSERT INTO Ingredients VALUES (NULL, 'Borlotti Beans');
INSERT INTO Ingredients VALUES (NULL, 'Bouquet Garni');
INSERT INTO Ingredients VALUES (NULL, 'Bowtie Pasta');
INSERT INTO Ingredients VALUES (NULL, 'Braeburn Apples');
INSERT INTO Ingredients VALUES (NULL, 'Bramley Apples');
INSERT INTO Ingredients VALUES (NULL, 'Brandy');
INSERT INTO Ingredients VALUES (NULL, 'Bread');
INSERT INTO Ingredients VALUES (NULL, 'Breadcrumbs');
INSERT INTO Ingredients VALUES (NULL, 'Bread Rolls');
INSERT INTO Ingredients VALUES (NULL, 'Brie');
INSERT INTO Ingredients VALUES (NULL, 'Broad Beans');
INSERT INTO Ingredients VALUES (NULL, 'Broccoli');
INSERT INTO Ingredients VALUES (NULL, 'Brown Lentils');
INSERT INTO Ingredients VALUES (NULL, 'Brown Rice');
INSERT INTO Ingredients VALUES (NULL, 'Brown Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Brussels Sprouts');
INSERT INTO Ingredients VALUES (NULL, 'Buckwheat');
INSERT INTO Ingredients VALUES (NULL, 'Bulgur Wheat');
INSERT INTO Ingredients VALUES (NULL, 'Bun');
INSERT INTO Ingredients VALUES (NULL, 'Buns');
INSERT INTO Ingredients VALUES (NULL, 'Butter');
INSERT INTO Ingredients VALUES (NULL, 'Butter Beans');
INSERT INTO Ingredients VALUES (NULL, 'Butternut Squash');
INSERT INTO Ingredients VALUES (NULL, 'Cabbage');
INSERT INTO Ingredients VALUES (NULL, 'Cacao');
INSERT INTO Ingredients VALUES (NULL, 'Cajun');
INSERT INTO Ingredients VALUES (NULL, 'Candied Peel');
INSERT INTO Ingredients VALUES (NULL, 'Canned Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Cannellini Beans');
INSERT INTO Ingredients VALUES (NULL, 'Canola Oil');
INSERT INTO Ingredients VALUES (NULL, 'Capers');
INSERT INTO Ingredients VALUES (NULL, 'Caramel');
INSERT INTO Ingredients VALUES (NULL, 'Caramel Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Caraway Seed');
INSERT INTO Ingredients VALUES (NULL, 'Cardamom');
INSERT INTO Ingredients VALUES (NULL, 'Carrots');
INSERT INTO Ingredients VALUES (NULL, 'Cashew Nuts');
INSERT INTO Ingredients VALUES (NULL, 'Cashews');
INSERT INTO Ingredients VALUES (NULL, 'Caster Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Cayenne Pepper');
INSERT INTO Ingredients VALUES (NULL, 'Celeriac');
INSERT INTO Ingredients VALUES (NULL, 'Celery');
INSERT INTO Ingredients VALUES (NULL, 'Celery Salt');
INSERT INTO Ingredients VALUES (NULL, 'Challots');
INSERT INTO Ingredients VALUES (NULL, 'Charlotte Potatoes');
INSERT INTO Ingredients VALUES (NULL, 'Cheddar Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Cheese Curds');
INSERT INTO Ingredients VALUES (NULL, 'Cheese Slices');
INSERT INTO Ingredients VALUES (NULL, 'Cherry');
INSERT INTO Ingredients VALUES (NULL, 'Cherry Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Chestnut Mushroom');
INSERT INTO Ingredients VALUES (NULL, 'Chestnuts');
INSERT INTO Ingredients VALUES (NULL, 'Chicken');
INSERT INTO Ingredients VALUES (NULL, 'Chicken Breast');
INSERT INTO Ingredients VALUES (NULL, 'Chicken Breasts');
INSERT INTO Ingredients VALUES (NULL, 'Chicken Legs');
INSERT INTO Ingredients VALUES (NULL, 'Chicken Stock');
INSERT INTO Ingredients VALUES (NULL, 'Chicken Stock Concentrate');
INSERT INTO Ingredients VALUES (NULL, 'Chicken Stock Cube');
INSERT INTO Ingredients VALUES (NULL, 'Chicken Thighs');
INSERT INTO Ingredients VALUES (NULL, 'Chickpeas');
INSERT INTO Ingredients VALUES (NULL, 'Chili Powder');
INSERT INTO Ingredients VALUES (NULL, 'Chilled Butter');
INSERT INTO Ingredients VALUES (NULL, 'Chilli');
INSERT INTO Ingredients VALUES (NULL, 'Chilli Powder');
INSERT INTO Ingredients VALUES (NULL, 'Chinese Broccoli');
INSERT INTO Ingredients VALUES (NULL, 'Chives');
INSERT INTO Ingredients VALUES (NULL, 'Chocolate Chips');
INSERT INTO Ingredients VALUES (NULL, 'Chopped Onion');
INSERT INTO Ingredients VALUES (NULL, 'Chopped Parsley');
INSERT INTO Ingredients VALUES (NULL, 'Chopped Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Chorizo');
INSERT INTO Ingredients VALUES (NULL, 'Christmas Pudding');
INSERT INTO Ingredients VALUES (NULL, 'Ciabatta');
INSERT INTO Ingredients VALUES (NULL, 'Cider');
INSERT INTO Ingredients VALUES (NULL, 'Cilantro');
INSERT INTO Ingredients VALUES (NULL, 'Cinnamon');
INSERT INTO Ingredients VALUES (NULL, 'Cinnamon Stick');
INSERT INTO Ingredients VALUES (NULL, 'Clams');
INSERT INTO Ingredients VALUES (NULL, 'Clotted Cream');
INSERT INTO Ingredients VALUES (NULL, 'Cloves');
INSERT INTO Ingredients VALUES (NULL, 'Cocoa');
INSERT INTO Ingredients VALUES (NULL, 'Coconut Cream');
INSERT INTO Ingredients VALUES (NULL, 'Coconut Milk');
INSERT INTO Ingredients VALUES (NULL, 'Coco Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Cod');
INSERT INTO Ingredients VALUES (NULL, 'Colby Jack Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Cold Water');
INSERT INTO Ingredients VALUES (NULL, 'Condensed Milk');
INSERT INTO Ingredients VALUES (NULL, 'Cooking wine');
INSERT INTO Ingredients VALUES (NULL, 'Coriander');
INSERT INTO Ingredients VALUES (NULL, 'Coriander Leaves');
INSERT INTO Ingredients VALUES (NULL, 'Coriander Seeds');
INSERT INTO Ingredients VALUES (NULL, 'Corn Flour');
INSERT INTO Ingredients VALUES (NULL, 'Cornstarch');
INSERT INTO Ingredients VALUES (NULL, 'Corn Tortillas');
INSERT INTO Ingredients VALUES (NULL, 'Courgettes');
INSERT INTO Ingredients VALUES (NULL, 'Couscous');
INSERT INTO Ingredients VALUES (NULL, 'Cream');
INSERT INTO Ingredients VALUES (NULL, 'Cream Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Creamed Corn');
INSERT INTO Ingredients VALUES (NULL, 'Creme Fraiche');
INSERT INTO Ingredients VALUES (NULL, 'Crusty Bread');
INSERT INTO Ingredients VALUES (NULL, 'Cubed Feta Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Cucumber');
INSERT INTO Ingredients VALUES (NULL, 'Cumin');
INSERT INTO Ingredients VALUES (NULL, 'Cumin Seeds');
INSERT INTO Ingredients VALUES (NULL, 'Currants');
INSERT INTO Ingredients VALUES (NULL, 'Curry Powder');
INSERT INTO Ingredients VALUES (NULL, 'Custard');
INSERT INTO Ingredients VALUES (NULL, 'Custard Powder');
INSERT INTO Ingredients VALUES (NULL, 'Dark Brown Soft Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Dark Brown Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Dark Chocolate');
INSERT INTO Ingredients VALUES (NULL, 'Dark Chocolate Chips');
INSERT INTO Ingredients VALUES (NULL, 'Dark Rum');
INSERT INTO Ingredients VALUES (NULL, 'Dark Soft Brown Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Dark Soy Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Demerara Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Desiccated Coconut');
INSERT INTO Ingredients VALUES (NULL, 'Diced Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Digestive Biscuits');
INSERT INTO Ingredients VALUES (NULL, 'Dijon Mustard');
INSERT INTO Ingredients VALUES (NULL, 'Dill');
INSERT INTO Ingredients VALUES (NULL, 'Dill Pickles');
INSERT INTO Ingredients VALUES (NULL, 'Doner Meat');
INSERT INTO Ingredients VALUES (NULL, 'Doubanjiang');
INSERT INTO Ingredients VALUES (NULL, 'Double Cream');
INSERT INTO Ingredients VALUES (NULL, 'Dried Apricots');
INSERT INTO Ingredients VALUES (NULL, 'Dried Fruit');
INSERT INTO Ingredients VALUES (NULL, 'Dried Oregano');
INSERT INTO Ingredients VALUES (NULL, 'Dry White Wine');
INSERT INTO Ingredients VALUES (NULL, 'Duck');
INSERT INTO Ingredients VALUES (NULL, 'Duck Fat');
INSERT INTO Ingredients VALUES (NULL, 'Duck Legs');
INSERT INTO Ingredients VALUES (NULL, 'Duck Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Egg');
INSERT INTO Ingredients VALUES (NULL, 'Egg Plants');
INSERT INTO Ingredients VALUES (NULL, 'Egg Rolls');
INSERT INTO Ingredients VALUES (NULL, 'Eggs');
INSERT INTO Ingredients VALUES (NULL, 'Egg White');
INSERT INTO Ingredients VALUES (NULL, 'Egg Yolks');
INSERT INTO Ingredients VALUES (NULL, 'Enchilada Sauce');
INSERT INTO Ingredients VALUES (NULL, 'English Muffins');
INSERT INTO Ingredients VALUES (NULL, 'English Mustard');
INSERT INTO Ingredients VALUES (NULL, 'Extra Virgin Olive Oil');
INSERT INTO Ingredients VALUES (NULL, 'Fajita Seasoning');
INSERT INTO Ingredients VALUES (NULL, 'Farfalle');
INSERT INTO Ingredients VALUES (NULL, 'Fennel');
INSERT INTO Ingredients VALUES (NULL, 'Fennel Bulb');
INSERT INTO Ingredients VALUES (NULL, 'Fennel Seeds');
INSERT INTO Ingredients VALUES (NULL, 'Fenugreek');
INSERT INTO Ingredients VALUES (NULL, 'Fermented Black Beans');
INSERT INTO Ingredients VALUES (NULL, 'Feta');
INSERT INTO Ingredients VALUES (NULL, 'Fettuccine');
INSERT INTO Ingredients VALUES (NULL, 'Fideo');
INSERT INTO Ingredients VALUES (NULL, 'Figs');
INSERT INTO Ingredients VALUES (NULL, 'Filo Pastry');
INSERT INTO Ingredients VALUES (NULL, 'Fish Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Fish Stock');
INSERT INTO Ingredients VALUES (NULL, 'Flaked Almonds');
INSERT INTO Ingredients VALUES (NULL, 'Flax Eggs');
INSERT INTO Ingredients VALUES (NULL, 'Flour');
INSERT INTO Ingredients VALUES (NULL, 'Flour Tortilla');
INSERT INTO Ingredients VALUES (NULL, 'Floury Potatoes');
INSERT INTO Ingredients VALUES (NULL, 'Free-range Egg, Beaten');
INSERT INTO Ingredients VALUES (NULL, 'Free-range Eggs, Beaten');
INSERT INTO Ingredients VALUES (NULL, 'French Lentils');
INSERT INTO Ingredients VALUES (NULL, 'Fresh Basil');
INSERT INTO Ingredients VALUES (NULL, 'Freshly Chopped Parsley');
INSERT INTO Ingredients VALUES (NULL, 'Fresh Thyme');
INSERT INTO Ingredients VALUES (NULL, 'Fries');
INSERT INTO Ingredients VALUES (NULL, 'Fromage Frais');
INSERT INTO Ingredients VALUES (NULL, 'Frozen Peas');
INSERT INTO Ingredients VALUES (NULL, 'Fruit Mix');
INSERT INTO Ingredients VALUES (NULL, 'Full Fat Yogurt');
INSERT INTO Ingredients VALUES (NULL, 'Garam Masala');
INSERT INTO Ingredients VALUES (NULL, 'Garlic');
INSERT INTO Ingredients VALUES (NULL, 'Garlic Clove');
INSERT INTO Ingredients VALUES (NULL, 'Garlic Powder');
INSERT INTO Ingredients VALUES (NULL, 'Garlic Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Gelatine Leafs');
INSERT INTO Ingredients VALUES (NULL, 'Ghee');
INSERT INTO Ingredients VALUES (NULL, 'Gherkin Relish');
INSERT INTO Ingredients VALUES (NULL, 'Ginger');
INSERT INTO Ingredients VALUES (NULL, 'Ginger Cordial');
INSERT INTO Ingredients VALUES (NULL, 'Ginger Garlic Paste');
INSERT INTO Ingredients VALUES (NULL, 'Ginger Paste');
INSERT INTO Ingredients VALUES (NULL, 'Glace Cherry');
INSERT INTO Ingredients VALUES (NULL, 'Goat Meat');
INSERT INTO Ingredients VALUES (NULL, 'Goats Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Gochujang');
INSERT INTO Ingredients VALUES (NULL, 'Golden Syrup');
INSERT INTO Ingredients VALUES (NULL, 'Goose Fat');
INSERT INTO Ingredients VALUES (NULL, 'Gouda Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Grand Marnier');
INSERT INTO Ingredients VALUES (NULL, 'Granulated Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Grape Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Greek Yogurt');
INSERT INTO Ingredients VALUES (NULL, 'Green Beans');
INSERT INTO Ingredients VALUES (NULL, 'Green Chilli');
INSERT INTO Ingredients VALUES (NULL, 'Green Olives');
INSERT INTO Ingredients VALUES (NULL, 'Green Pepper');
INSERT INTO Ingredients VALUES (NULL, 'Green Red Lentils');
INSERT INTO Ingredients VALUES (NULL, 'Green Salsa');
INSERT INTO Ingredients VALUES (NULL, 'Ground Almonds');
INSERT INTO Ingredients VALUES (NULL, 'Ground Beef');
INSERT INTO Ingredients VALUES (NULL, 'Ground Cumin');
INSERT INTO Ingredients VALUES (NULL, 'Ground Ginger');
INSERT INTO Ingredients VALUES (NULL, 'Ground Pork');
INSERT INTO Ingredients VALUES (NULL, 'Gruyère');
INSERT INTO Ingredients VALUES (NULL, 'Haddock');
INSERT INTO Ingredients VALUES (NULL, 'Ham');
INSERT INTO Ingredients VALUES (NULL, 'Hard Taco Shells');
INSERT INTO Ingredients VALUES (NULL, 'Haricot Beans');
INSERT INTO Ingredients VALUES (NULL, 'Harissa Spice');
INSERT INTO Ingredients VALUES (NULL, 'Hazlenuts');
INSERT INTO Ingredients VALUES (NULL, 'Heavy Cream');
INSERT INTO Ingredients VALUES (NULL, 'Herring');
INSERT INTO Ingredients VALUES (NULL, 'Honey');
INSERT INTO Ingredients VALUES (NULL, 'Horseradish');
INSERT INTO Ingredients VALUES (NULL, 'Hot Beef Stock');
INSERT INTO Ingredients VALUES (NULL, 'Hotsauce');
INSERT INTO Ingredients VALUES (NULL, 'Iceberg Lettuce');
INSERT INTO Ingredients VALUES (NULL, 'Ice Cream');
INSERT INTO Ingredients VALUES (NULL, 'Icing Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Italian Fennel Sausages');
INSERT INTO Ingredients VALUES (NULL, 'Italian Seasoning');
INSERT INTO Ingredients VALUES (NULL, 'Jalapeno');
INSERT INTO Ingredients VALUES (NULL, 'Jam');
INSERT INTO Ingredients VALUES (NULL, 'Jasmine Rice');
INSERT INTO Ingredients VALUES (NULL, 'Jerk');
INSERT INTO Ingredients VALUES (NULL, 'Jerusalem Artichokes');
INSERT INTO Ingredients VALUES (NULL, 'Kale');
INSERT INTO Ingredients VALUES (NULL, 'Khus Khus');
INSERT INTO Ingredients VALUES (NULL, 'Kidney Beans');
INSERT INTO Ingredients VALUES (NULL, 'Kielbasa');
INSERT INTO Ingredients VALUES (NULL, 'King Prawns');
INSERT INTO Ingredients VALUES (NULL, 'Kosher Salt');
INSERT INTO Ingredients VALUES (NULL, 'Lamb');
INSERT INTO Ingredients VALUES (NULL, 'Lamb Kidney');
INSERT INTO Ingredients VALUES (NULL, 'Lamb Leg');
INSERT INTO Ingredients VALUES (NULL, 'Lamb Loin Chops');
INSERT INTO Ingredients VALUES (NULL, 'Lamb Mince');
INSERT INTO Ingredients VALUES (NULL, 'Lamb Shoulder');
INSERT INTO Ingredients VALUES (NULL, 'Lard');
INSERT INTO Ingredients VALUES (NULL, 'Lasagne Sheets');
INSERT INTO Ingredients VALUES (NULL, 'Lean Minced Beef');
INSERT INTO Ingredients VALUES (NULL, 'Leek');
INSERT INTO Ingredients VALUES (NULL, 'Lemon');
INSERT INTO Ingredients VALUES (NULL, 'Lemon Juice');
INSERT INTO Ingredients VALUES (NULL, 'Lemons');
INSERT INTO Ingredients VALUES (NULL, 'Lemon Zest');
INSERT INTO Ingredients VALUES (NULL, 'Lentils');
INSERT INTO Ingredients VALUES (NULL, 'Lettuce');
INSERT INTO Ingredients VALUES (NULL, 'Light Brown Soft Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Light Rum');
INSERT INTO Ingredients VALUES (NULL, 'Lime');
INSERT INTO Ingredients VALUES (NULL, 'Linguine Pasta');
INSERT INTO Ingredients VALUES (NULL, 'Little Gem Lettuce');
INSERT INTO Ingredients VALUES (NULL, 'Lacaroni');
INSERT INTO Ingredients VALUES (NULL, 'Lackerel');
INSERT INTO Ingredients VALUES (NULL, 'Ladras Paste');
INSERT INTO Ingredients VALUES (NULL, 'Lalt Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'Laple Syrup');
INSERT INTO Ingredients VALUES (NULL, 'Larjoram');
INSERT INTO Ingredients VALUES (NULL, 'Lars Bar');
INSERT INTO Ingredients VALUES (NULL, 'Larzipan');
INSERT INTO Ingredients VALUES (NULL, 'Lascarpone');
INSERT INTO Ingredients VALUES (NULL, 'Lassaman Curry Paste');
INSERT INTO Ingredients VALUES (NULL, 'Layonnaise');
INSERT INTO Ingredients VALUES (NULL, 'Ledjool Dates');
INSERT INTO Ingredients VALUES (NULL, 'Leringue Nests');
INSERT INTO Ingredients VALUES (NULL, 'Lilk');
INSERT INTO Ingredients VALUES (NULL, 'Lilk Chocolate');
INSERT INTO Ingredients VALUES (NULL, 'Linced Beef');
INSERT INTO Ingredients VALUES (NULL, 'Linced Garlic');
INSERT INTO Ingredients VALUES (NULL, 'Linced Pork');
INSERT INTO Ingredients VALUES (NULL, 'Lincemeat');
INSERT INTO Ingredients VALUES (NULL, 'Liniature Marshmallows');
INSERT INTO Ingredients VALUES (NULL, 'Lint');
INSERT INTO Ingredients VALUES (NULL, 'Lirin');
INSERT INTO Ingredients VALUES (NULL, 'Lixed Grain');
INSERT INTO Ingredients VALUES (NULL, 'Lixed Peel');
INSERT INTO Ingredients VALUES (NULL, 'Lixed Spice');
INSERT INTO Ingredients VALUES (NULL, 'Lonkfish');
INSERT INTO Ingredients VALUES (NULL, 'Lonterey Jack Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Lozzarella');
INSERT INTO Ingredients VALUES (NULL, 'Lozzarella Balls');
INSERT INTO Ingredients VALUES (NULL, 'Luffins');
INSERT INTO Ingredients VALUES (NULL, 'Lulukhiyah');
INSERT INTO Ingredients VALUES (NULL, 'Luscovado Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Lushrooms');
INSERT INTO Ingredients VALUES (NULL, 'Lussels');
INSERT INTO Ingredients VALUES (NULL, 'Lustard');
INSERT INTO Ingredients VALUES (NULL, 'Lustard Powder');
INSERT INTO Ingredients VALUES (NULL, 'Lustard Seeds');
INSERT INTO Ingredients VALUES (NULL, 'Milk');
INSERT INTO Ingredients VALUES (NULL, 'Naan Bread');
INSERT INTO Ingredients VALUES (NULL, 'Noodles');
INSERT INTO Ingredients VALUES (NULL, 'Nutmeg');
INSERT INTO Ingredients VALUES (NULL, 'Oatmeal');
INSERT INTO Ingredients VALUES (NULL, 'Oats');
INSERT INTO Ingredients VALUES (NULL, 'Oil');
INSERT INTO Ingredients VALUES (NULL, 'Olive Oil');
INSERT INTO Ingredients VALUES (NULL, 'Onion');
INSERT INTO Ingredients VALUES (NULL, 'Onions');
INSERT INTO Ingredients VALUES (NULL, 'Onion Salt');
INSERT INTO Ingredients VALUES (NULL, 'Orange');
INSERT INTO Ingredients VALUES (NULL, 'Orange Blossom Water');
INSERT INTO Ingredients VALUES (NULL, 'Orange Zest');
INSERT INTO Ingredients VALUES (NULL, 'Oregano');
INSERT INTO Ingredients VALUES (NULL, 'Oxtail');
INSERT INTO Ingredients VALUES (NULL, 'Oysters');
INSERT INTO Ingredients VALUES (NULL, 'Oyster Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Paccheri Pasta');
INSERT INTO Ingredients VALUES (NULL, 'Paella Rice');
INSERT INTO Ingredients VALUES (NULL, 'Paneer');
INSERT INTO Ingredients VALUES (NULL, 'Pappardelle Pasta');
INSERT INTO Ingredients VALUES (NULL, 'Paprika');
INSERT INTO Ingredients VALUES (NULL, 'Parma Ham');
INSERT INTO Ingredients VALUES (NULL, 'Parmesan');
INSERT INTO Ingredients VALUES (NULL, 'Parmesan Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Parmigiano-reggiano');
INSERT INTO Ingredients VALUES (NULL, 'Parsley');
INSERT INTO Ingredients VALUES (NULL, 'Passata');
INSERT INTO Ingredients VALUES (NULL, 'Peaches');
INSERT INTO Ingredients VALUES (NULL, 'Peanut Brittle');
INSERT INTO Ingredients VALUES (NULL, 'Peanut Butter');
INSERT INTO Ingredients VALUES (NULL, 'Peanut Cookies');
INSERT INTO Ingredients VALUES (NULL, 'Peanut Oil');
INSERT INTO Ingredients VALUES (NULL, 'Peanuts');
INSERT INTO Ingredients VALUES (NULL, 'Pears');
INSERT INTO Ingredients VALUES (NULL, 'Peas');
INSERT INTO Ingredients VALUES (NULL, 'Pecan Nuts');
INSERT INTO Ingredients VALUES (NULL, 'Pecorino');
INSERT INTO Ingredients VALUES (NULL, 'Penne Rigate');
INSERT INTO Ingredients VALUES (NULL, 'Pepper');
INSERT INTO Ingredients VALUES (NULL, 'Persian Cucumber');
INSERT INTO Ingredients VALUES (NULL, 'Pickle Juice');
INSERT INTO Ingredients VALUES (NULL, 'Pilchards');
INSERT INTO Ingredients VALUES (NULL, 'Pine Nuts');
INSERT INTO Ingredients VALUES (NULL, 'Pink Food Colouring');
INSERT INTO Ingredients VALUES (NULL, 'Pinto Beans');
INSERT INTO Ingredients VALUES (NULL, 'Pita Bread');
INSERT INTO Ingredients VALUES (NULL, 'Pitted Black Olives');
INSERT INTO Ingredients VALUES (NULL, 'Plain Chocolate');
INSERT INTO Ingredients VALUES (NULL, 'Plain Flour');
INSERT INTO Ingredients VALUES (NULL, 'Plum Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Polish Sausage');
INSERT INTO Ingredients VALUES (NULL, 'Pork');
INSERT INTO Ingredients VALUES (NULL, 'Pork Chops');
INSERT INTO Ingredients VALUES (NULL, 'Potatoe Buns');
INSERT INTO Ingredients VALUES (NULL, 'Potatoes');
INSERT INTO Ingredients VALUES (NULL, 'Potato Starch');
INSERT INTO Ingredients VALUES (NULL, 'Powdered Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Prawns');
INSERT INTO Ingredients VALUES (NULL, 'Pretzels');
INSERT INTO Ingredients VALUES (NULL, 'Prosciutto');
INSERT INTO Ingredients VALUES (NULL, 'Puff Pastry');
INSERT INTO Ingredients VALUES (NULL, 'Pumpkin');
INSERT INTO Ingredients VALUES (NULL, 'Quinoa');
INSERT INTO Ingredients VALUES (NULL, 'Raisins');
INSERT INTO Ingredients VALUES (NULL, 'Rapeseed Oil');
INSERT INTO Ingredients VALUES (NULL, 'Ras el hanout');
INSERT INTO Ingredients VALUES (NULL, 'Raspberries');
INSERT INTO Ingredients VALUES (NULL, 'Raspberry Jam');
INSERT INTO Ingredients VALUES (NULL, 'Raw King Prawns');
INSERT INTO Ingredients VALUES (NULL, 'Red Chile Flakes');
INSERT INTO Ingredients VALUES (NULL, 'Red Chilli');
INSERT INTO Ingredients VALUES (NULL, 'Red Chilli Powder');
INSERT INTO Ingredients VALUES (NULL, 'Redcurrants');
INSERT INTO Ingredients VALUES (NULL, 'Red Food Colouring');
INSERT INTO Ingredients VALUES (NULL, 'Red Onions');
INSERT INTO Ingredients VALUES (NULL, 'Red Pepper');
INSERT INTO Ingredients VALUES (NULL, 'Red Pepper Flakes');
INSERT INTO Ingredients VALUES (NULL, 'Red Snapper');
INSERT INTO Ingredients VALUES (NULL, 'Red Wine');
INSERT INTO Ingredients VALUES (NULL, 'Red Wine Jelly');
INSERT INTO Ingredients VALUES (NULL, 'Red Wine Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'Refried Beans');
INSERT INTO Ingredients VALUES (NULL, 'Rhubarb');
INSERT INTO Ingredients VALUES (NULL, 'Rice');
INSERT INTO Ingredients VALUES (NULL, 'Rice Krispies');
INSERT INTO Ingredients VALUES (NULL, 'Rice Noodles');
INSERT INTO Ingredients VALUES (NULL, 'Rice Stick Noodles');
INSERT INTO Ingredients VALUES (NULL, 'Rice Vermicelli');
INSERT INTO Ingredients VALUES (NULL, 'Rice Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'Rice wine');
INSERT INTO Ingredients VALUES (NULL, 'Ricotta');
INSERT INTO Ingredients VALUES (NULL, 'Rigatoni');
INSERT INTO Ingredients VALUES (NULL, 'Roasted Vegetables');
INSERT INTO Ingredients VALUES (NULL, 'Rocket');
INSERT INTO Ingredients VALUES (NULL, 'Rolled Oats');
INSERT INTO Ingredients VALUES (NULL, 'Rosemary');
INSERT INTO Ingredients VALUES (NULL, 'Rose water');
INSERT INTO Ingredients VALUES (NULL, 'Rum');
INSERT INTO Ingredients VALUES (NULL, 'Saffron');
INSERT INTO Ingredients VALUES (NULL, 'Sage');
INSERT INTO Ingredients VALUES (NULL, 'Sake');
INSERT INTO Ingredients VALUES (NULL, 'Salmon');
INSERT INTO Ingredients VALUES (NULL, 'Salsa');
INSERT INTO Ingredients VALUES (NULL, 'Salt');
INSERT INTO Ingredients VALUES (NULL, 'Salt Cod');
INSERT INTO Ingredients VALUES (NULL, 'Salted Butter');
INSERT INTO Ingredients VALUES (NULL, 'Sardines');
INSERT INTO Ingredients VALUES (NULL, 'Sauerkraut');
INSERT INTO Ingredients VALUES (NULL, 'Sausages');
INSERT INTO Ingredients VALUES (NULL, 'Scallions');
INSERT INTO Ingredients VALUES (NULL, 'Scotch Bonnet');
INSERT INTO Ingredients VALUES (NULL, 'Sea Salt');
INSERT INTO Ingredients VALUES (NULL, 'Self-raising Flour');
INSERT INTO Ingredients VALUES (NULL, 'Semi-skimmed Milk');
INSERT INTO Ingredients VALUES (NULL, 'Sesame Seed');
INSERT INTO Ingredients VALUES (NULL, 'Sesame Seed Burger Buns');
INSERT INTO Ingredients VALUES (NULL, 'Sesame Seed Oil');
INSERT INTO Ingredients VALUES (NULL, 'Shallots');
INSERT INTO Ingredients VALUES (NULL, 'Sherry');
INSERT INTO Ingredients VALUES (NULL, 'Shiitake Mushrooms');
INSERT INTO Ingredients VALUES (NULL, 'Shortcrust Pastry');
INSERT INTO Ingredients VALUES (NULL, 'Shortening');
INSERT INTO Ingredients VALUES (NULL, 'Shredded Mexican Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Shredded Monterey Jack Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Sichuan Pepper');
INSERT INTO Ingredients VALUES (NULL, 'Single Cream');
INSERT INTO Ingredients VALUES (NULL, 'Small Potatoes');
INSERT INTO Ingredients VALUES (NULL, 'Smoked Haddock');
INSERT INTO Ingredients VALUES (NULL, 'Smoked Paprika');
INSERT INTO Ingredients VALUES (NULL, 'Smoked Salmon');
INSERT INTO Ingredients VALUES (NULL, 'Smoky Paprika');
INSERT INTO Ingredients VALUES (NULL, 'Sour Cream');
INSERT INTO Ingredients VALUES (NULL, 'Soya Milk');
INSERT INTO Ingredients VALUES (NULL, 'Soy Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Spaghetti');
INSERT INTO Ingredients VALUES (NULL, 'Spinach');
INSERT INTO Ingredients VALUES (NULL, 'Spring Onions');
INSERT INTO Ingredients VALUES (NULL, 'Squash');
INSERT INTO Ingredients VALUES (NULL, 'Squid');
INSERT INTO Ingredients VALUES (NULL, 'Sriracha');
INSERT INTO Ingredients VALUES (NULL, 'Star Anise');
INSERT INTO Ingredients VALUES (NULL, 'Starch');
INSERT INTO Ingredients VALUES (NULL, 'Stilton Cheese');
INSERT INTO Ingredients VALUES (NULL, 'Stir-fry Vegetables');
INSERT INTO Ingredients VALUES (NULL, 'Stout');
INSERT INTO Ingredients VALUES (NULL, 'Strawberries');
INSERT INTO Ingredients VALUES (NULL, 'Suet');
INSERT INTO Ingredients VALUES (NULL, 'Sugar');
INSERT INTO Ingredients VALUES (NULL, 'Sugar Snap Peas');
INSERT INTO Ingredients VALUES (NULL, 'Sultanas');
INSERT INTO Ingredients VALUES (NULL, 'Sun-Dried Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Sunflower Oil');
INSERT INTO Ingredients VALUES (NULL, 'Sushi Rice');
INSERT INTO Ingredients VALUES (NULL, 'Swede');
INSERT INTO Ingredients VALUES (NULL, 'Sweetcorn');
INSERT INTO Ingredients VALUES (NULL, 'Sweet Potatoes');
INSERT INTO Ingredients VALUES (NULL, 'Tabasco Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Tagliatelle');
INSERT INTO Ingredients VALUES (NULL, 'Tahini');
INSERT INTO Ingredients VALUES (NULL, 'Tamarind Ball');
INSERT INTO Ingredients VALUES (NULL, 'Tamarind Paste');
INSERT INTO Ingredients VALUES (NULL, 'Tarragon Leaves');
INSERT INTO Ingredients VALUES (NULL, 'Thai Fish Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Thai Green Curry Paste');
INSERT INTO Ingredients VALUES (NULL, 'Thai Red Curry Paste');
INSERT INTO Ingredients VALUES (NULL, 'Thyme');
INSERT INTO Ingredients VALUES (NULL, 'Tiger Prawns');
INSERT INTO Ingredients VALUES (NULL, 'Tinned Tomatos');
INSERT INTO Ingredients VALUES (NULL, 'Toffee Popcorn');
INSERT INTO Ingredients VALUES (NULL, 'Tofu');
INSERT INTO Ingredients VALUES (NULL, 'Tomato');
INSERT INTO Ingredients VALUES (NULL, 'Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Tomato Ketchup');
INSERT INTO Ingredients VALUES (NULL, 'Tomato Puree');
INSERT INTO Ingredients VALUES (NULL, 'Tomato Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Toor Dal');
INSERT INTO Ingredients VALUES (NULL, 'Tortillas');
INSERT INTO Ingredients VALUES (NULL, 'Treacle');
INSERT INTO Ingredients VALUES (NULL, 'Tripe');
INSERT INTO Ingredients VALUES (NULL, 'Truffle Oil');
INSERT INTO Ingredients VALUES (NULL, 'Tuna');
INSERT INTO Ingredients VALUES (NULL, 'Turkey Mince');
INSERT INTO Ingredients VALUES (NULL, 'Turmeric');
INSERT INTO Ingredients VALUES (NULL, 'Turmeric Powder');
INSERT INTO Ingredients VALUES (NULL, 'Turnips');
INSERT INTO Ingredients VALUES (NULL, 'Udon Noodles');
INSERT INTO Ingredients VALUES (NULL, 'Unsalted Butter');
INSERT INTO Ingredients VALUES (NULL, 'Vanilla');
INSERT INTO Ingredients VALUES (NULL, 'Vanilla Extract');
INSERT INTO Ingredients VALUES (NULL, 'Veal');
INSERT INTO Ingredients VALUES (NULL, 'Vegan Butter');
INSERT INTO Ingredients VALUES (NULL, 'Vegetable Oil');
INSERT INTO Ingredients VALUES (NULL, 'Vegetable Stock');
INSERT INTO Ingredients VALUES (NULL, 'Vegetable Stock Cube');
INSERT INTO Ingredients VALUES (NULL, 'Vermicelli Pasta');
INSERT INTO Ingredients VALUES (NULL, 'Vinaigrette Dressing');
INSERT INTO Ingredients VALUES (NULL, 'Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'Vine Leaves');
INSERT INTO Ingredients VALUES (NULL, 'Vine Tomatoes');
INSERT INTO Ingredients VALUES (NULL, 'Walnuts');
INSERT INTO Ingredients VALUES (NULL, 'Warm Water');
INSERT INTO Ingredients VALUES (NULL, 'Water');
INSERT INTO Ingredients VALUES (NULL, 'Water Chestnut');
INSERT INTO Ingredients VALUES (NULL, 'Wheat Flour');
INSERT INTO Ingredients VALUES (NULL, 'White Chocolate');
INSERT INTO Ingredients VALUES (NULL, 'White Chocolate Chips');
INSERT INTO Ingredients VALUES (NULL, 'White Fish');
INSERT INTO Ingredients VALUES (NULL, 'White Fish Fillets');
INSERT INTO Ingredients VALUES (NULL, 'White Flour');
INSERT INTO Ingredients VALUES (NULL, 'White Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'White Wine');
INSERT INTO Ingredients VALUES (NULL, 'White Wine Vinegar');
INSERT INTO Ingredients VALUES (NULL, 'Wholegrain Bread');
INSERT INTO Ingredients VALUES (NULL, 'Whole Milk');
INSERT INTO Ingredients VALUES (NULL, 'Whole Wheat');
INSERT INTO Ingredients VALUES (NULL, 'Whole Wheat Flour');
INSERT INTO Ingredients VALUES (NULL, 'Wild Mushrooms');
INSERT INTO Ingredients VALUES (NULL, 'Wonton Skin');
INSERT INTO Ingredients VALUES (NULL, 'Wood Ear Mushrooms');
INSERT INTO Ingredients VALUES (NULL, 'Worcestershire Sauce');
INSERT INTO Ingredients VALUES (NULL, 'Yeast');
INSERT INTO Ingredients VALUES (NULL, 'Yellow Food Colouring');
INSERT INTO Ingredients VALUES (NULL, 'Yellow Onion');
INSERT INTO Ingredients VALUES (NULL, 'Yellow Pepper');
INSERT INTO Ingredients VALUES (NULL, 'Yogurt');
INSERT INTO Ingredients VALUES (NULL, 'Yukon Gold Potatoes');
INSERT INTO Ingredients VALUES (NULL, 'Zucchini');