INSERT INTO Measurements VALUES (NULL, 'g', 'gram', 'grams');
INSERT INTO Measurements VALUES (NULL, 'kg', 'kilogram', 'kilograms');
INSERT INTO Measurements VALUES (NULL, 'ml', 'milliliter', 'milliliters');
INSERT INTO Measurements VALUES (NULL, 'dl', 'deciliter', 'deciliters');
INSERT INTO Measurements VALUES (NULL, 'l', 'liter', 'liters');
INSERT INTO Measurements VALUES (NULL, 'tsp', 'teaspoon', 'teaspoons');
INSERT INTO Measurements VALUES (NULL, 'tbsp', 'tablespoon', 'tablespoons');
INSERT INTO Measurements VALUES (NULL, 'oz', 'ounce', 'ounces');
INSERT INTO Measurements VALUES (NULL, 'fl. oz', 'fluid ounce', 'fluid ounces');
INSERT INTO Measurements VALUES (NULL, 'c', 'cup', 'cups');
INSERT INTO Measurements VALUES (NULL, 'qt', 'quart', 'quatrs');
INSERT INTO Measurements VALUES (NULL, 'pt', 'pint', 'pints');
INSERT INTO Measurements VALUES (NULL, 'gal', 'gallon', 'gallons');
INSERT INTO Measurements VALUES (NULL, 'lb', 'pound', 'pounds');
INSERT INTO Measurements VALUES (NULL, 'piece', 'piece', 'pieces');
INSERT INTO Measurements VALUES (NULL, 'as required', 'as required', 'as required');
INSERT INTO Measurements VALUES (NULL, 'pinch','pinch', 'pinches');
INSERT INTO Measurements VALUES (NULL, 'dash','dash', 'dashes');
INSERT INTO Measurements VALUES (NULL, 'smidgen','smidgen', 'smidgens');
INSERT INTO Measurements VALUES (NULL, 'stick','stick', 'sticks');
INSERT INTO Measurements VALUES (NULL, '', '', '');