import { Meal } from '../src/recipe-service';

export const testRecipes = [
  {
    name: 'African Breakfast',
    drink: 'Water',
    category: 1,
    area: 1,
    instructions: 'Bla bla bla bla',
    thumb: null,
    youtube: null,
    ingredients: [
      { name: 'Bread', number: 2, abbreviation: 21 },
      { name: 'Egg', number: 2, abbreviation: 21 },
    ],
  },
  {
    name: 'Asian Dinner',
    drink: 'Wine',
    category: 4,
    area: 3,
    instructions: 'Bla bla bla bla',
    thumb: null,
    youtube: null,
    ingredients: [{ name: 'Pasta', number: 100, abbreviation: 1 }],
  },
  {
    name: 'Another Asian Dinner',
    drink: 'Wine',
    category: 4,
    area: 3,
    instructions: 'Amazingly similar to the other Asian Dinner',
    thumb: null,
    youtube: null,
    ingredients: [{ name: 'Pasta', number: 100, abbreviation: 1 }],
  },
];

export const currentRecipes: Meal[] = [
  {
    id: 1,
    name: 'African Breakfast',
    drink: 'Water',
    category: 'Breakfast',
    area: 'African',
    instructions: 'Bla bla bla bla',
    thumb: null,
    youtube: null,
    likes: 0,
    ingredients: [
      { name: 'Bread', number: 2, abbreviation: '' },
      { name: 'Egg', number: 2, abbreviation: '' },
    ],
  },
  {
    id: 2,
    name: 'Asian Dinner',
    drink: 'Wine',
    category: 'Dinner',
    area: 'Asian',
    instructions: 'Bla bla bla bla',
    thumb: null,
    youtube: null,
    likes: 0,
    ingredients: [{ name: 'Pasta', number: 100, abbreviation: 'g' }],
  },
];

export const createUsers = [
  {
    username: 'Charlie123',
    password: 'Password123',
    admin: 1,
  },
  {
    username: 'Matheus123',
    password: 'Password123',
    admin: 0,
  },
  {
    username: 'Loki123',
    password: 'Password123',
    admin: 0,
  },
];
export const getUsers = [
  {
    id: 1,
    username: 'Charlie123',
    password: 'Password123',
  },
];
export const getAllUsers = [
  {
    username: 'Charlie123',
    password: 'Password123',
  },
  {
    username: 'Matheus123',
    password: 'Password123',
  },
];

export const wrongpass = [
  {
    id: 1,
    username: 'Charlie123',
    password: 'feilpassord',
  },
];

export const allMeasuremnts = [
  { id: 1, abbreviation: 'g', singular: 'gram', measurement: 'grams' },
  { id: 2, abbreviation: 'kg', singular: 'kilogram', measurement: 'kilograms' },
  { id: 3, abbreviation: 'ml', singular: 'milliliter', measurement: 'milliliters' },
  { id: 4, abbreviation: 'dl', singular: 'deciliter', measurement: 'deciliters' },
  { id: 5, abbreviation: 'l', singular: 'liter', measurement: 'liters' },
  { id: 6, abbreviation: 'tsp', singular: 'teaspoon', measurement: 'teaspoons' },
  { id: 7, abbreviation: 'tbsp', singular: 'tablespoon', measurement: 'tablespoons' },
  { id: 8, abbreviation: 'oz', singular: 'ounce', measurement: 'ounces' },
  { id: 9, abbreviation: 'fl. oz', singular: 'fluid ounce', measurement: 'fluid ounces' },
  { id: 10, abbreviation: 'c', singular: 'cup', measurement: 'cups' },
  { id: 11, abbreviation: 'qt', singular: 'quart', measurement: 'quatrs' },
  { id: 12, abbreviation: 'pt', singular: 'pint', measurement: 'pints' },
  { id: 13, abbreviation: 'gal', singular: 'gallon', measurement: 'gallons' },
  { id: 14, abbreviation: 'lb', singular: 'pound', measurement: 'pounds' },
  { id: 15, abbreviation: 'piece', singular: 'piece', measurement: 'pieces' },
  { id: 16, abbreviation: 'as required', singular: 'as required', measurement: 'as required' },
  { id: 17, abbreviation: 'pinch', singular: 'pinch', measurement: 'pinches' },
  { id: 18, abbreviation: 'dash', singular: 'dash', measurement: 'dashes' },
  { id: 19, abbreviation: 'smidgen', singular: 'smidgen', measurement: 'smidgens' },
  { id: 20, abbreviation: 'stick', singular: 'stick', measurement: 'sticks' },
  { id: 21, abbreviation: '', singular: '', measurement: '' },
];

export const allCategories = [
  { id: 1, category: 'Breakfast' },
  { id: 2, category: 'Lunch' },
  { id: 3, category: 'Appetisers' },
  { id: 4, category: 'Dinner' },
  { id: 5, category: 'Snack' },
  { id: 6, category: 'Soups' },
  { id: 7, category: 'Salads' },
  { id: 8, category: 'Sides' },
  { id: 9, category: 'Vegetarian' },
  { id: 10, category: 'Vegan' },
  { id: 11, category: 'Beef' },
  { id: 12, category: 'Chicken' },
  { id: 13, category: 'Poultry' },
  { id: 14, category: 'Pork' },
  { id: 15, category: 'Lamb' },
  { id: 16, category: 'Goat' },
  { id: 17, category: 'Fish' },
  { id: 18, category: 'Seafood' },
  { id: 19, category: 'Pasta' },
  { id: 20, category: 'Rice' },
  { id: 21, category: 'Noodles' },
  { id: 22, category: 'Casserole' },
  { id: 23, category: 'Barbeque' },
  { id: 24, category: 'Stir Fry' },
  { id: 25, category: 'Pizza' },
  { id: 26, category: 'Pie' },
  { id: 27, category: 'Burgers' },
  { id: 28, category: 'Sausages' },
  { id: 29, category: 'Mince' },
  { id: 30, category: 'Sauce' },
  { id: 31, category: 'Dips' },
  { id: 32, category: 'Condiments' },
  { id: 33, category: 'Bread' },
  { id: 34, category: 'Baking' },
  { id: 35, category: 'Muffins' },
  { id: 36, category: 'Cake' },
  { id: 37, category: 'Biscuits' },
  { id: 38, category: 'Sweets' },
  { id: 39, category: 'Desserts' },
  { id: 40, category: 'Ice Cream' },
  { id: 41, category: 'Drinks' },
  { id: 42, category: 'Sandwiches' },
  { id: 43, category: 'Wraps' },
  { id: 44, category: 'Miscellaneous' },
];

export const allAreaASC = [
  { id: 1, area: 'African' },
  { id: 2, area: 'American' },
  { id: 3, area: 'Asian' },
  { id: 4, area: 'Australian' },
  { id: 5, area: 'British' },
  { id: 6, area: 'Canadian' },
  { id: 7, area: 'Chinese' },
  { id: 8, area: 'Creole' },
  { id: 9, area: 'Croatian' },
  { id: 10, area: 'Danish' },
  { id: 11, area: 'Dutch' },
  { id: 12, area: 'European' },
  { id: 13, area: 'Egyptian' },
  { id: 14, area: 'French' },
  { id: 15, area: 'Fusion' },
  { id: 16, area: 'German' },
  { id: 17, area: 'Greek' },
  { id: 18, area: 'Hungarian' },
  { id: 19, area: 'Hispanic' },
  { id: 20, area: 'Icelandic' },
  { id: 21, area: 'Indian' },
  { id: 22, area: 'Indonesian' },
  { id: 23, area: 'Irish' },
  { id: 24, area: 'Italian' },
  { id: 25, area: 'Jamaican' },
  { id: 26, area: 'Japanese' },
  { id: 27, area: 'Kenyan' },
  { id: 28, area: 'Korean' },
  { id: 29, area: 'Lebanese' },
  { id: 30, area: 'Malaysian' },
  { id: 31, area: 'Mediterranean' },
  { id: 32, area: 'Mexican' },
  { id: 33, area: 'Middle Eastern' },
  { id: 34, area: 'Moroccan' },
  { id: 35, area: 'Norwegian' },
  { id: 36, area: 'Persain' },
  { id: 37, area: 'Polish' },
  { id: 38, area: 'Portuguese' },
  { id: 39, area: 'Russian' },
  { id: 40, area: 'Spanish' },
  { id: 41, area: 'Sri Lankan' },
  { id: 42, area: 'Swedish' },
  { id: 43, area: 'Thai' },
  { id: 44, area: 'Turkish' },
  { id: 45, area: 'Vietnamese' },
  { id: 46, area: 'Unknown' },
  { id: 47, area: 'Other' },
];
export const allIngredientsASC = [
  { id: 1, ingredient: 'Ackee' },
  { id: 3, ingredient: 'Allspice' },
  { id: 4, ingredient: 'Almond Extract' },
  { id: 5, ingredient: 'Almond Milk' },
  { id: 6, ingredient: 'Almonds' },
  { id: 7, ingredient: 'Ancho Chillies' },
  { id: 8, ingredient: 'Anchovy Fillet' },
  { id: 9, ingredient: 'Apple Cider Vinegar' },
  { id: 10, ingredient: 'Apples' },
  { id: 11, ingredient: 'Apricot' },
  { id: 12, ingredient: 'Apricot Jam' },
  { id: 13, ingredient: 'Asparagus' },
  { id: 14, ingredient: 'Aubergine' },
  { id: 2, ingredient: 'Avocado' },
  { id: 15, ingredient: 'Avocado' },
  { id: 16, ingredient: 'Baby Aubergine' },
  { id: 17, ingredient: 'Baby Plum Tomatoes' },
  { id: 18, ingredient: 'Baby Squid' },
  { id: 19, ingredient: 'Bacon' },
  { id: 20, ingredient: 'Baguette' },
  { id: 21, ingredient: 'Baked Beans' },
  { id: 22, ingredient: 'Baking Powder' },
  { id: 23, ingredient: 'Balsamic Vinegar' },
  { id: 24, ingredient: 'Banana' },
  { id: 25, ingredient: 'Barbeque Sauce' },
  { id: 26, ingredient: 'Basil' },
  { id: 27, ingredient: 'Basil Leaves' },
  { id: 28, ingredient: 'Basmati Rice' },
  { id: 29, ingredient: 'Bay Leaf' },
  { id: 30, ingredient: 'Bay Leaves' },
  { id: 31, ingredient: 'Bean Sprouts' },
  { id: 32, ingredient: 'Beef' },
  { id: 33, ingredient: 'Beef Brisket' },
  { id: 34, ingredient: 'Beef Fillet' },
  { id: 35, ingredient: 'Beef Gravy' },
  { id: 36, ingredient: 'Beef Kidney' },
  { id: 37, ingredient: 'Beef Shin' },
  { id: 38, ingredient: 'Beef Stock' },
  { id: 39, ingredient: 'Beef Stock Concentrate' },
  { id: 40, ingredient: 'Beetroot' },
  { id: 41, ingredient: 'Bicarbonate Of Soda' },
  { id: 42, ingredient: 'Biryani Masala' },
  { id: 43, ingredient: 'Black Beans' },
  { id: 45, ingredient: 'Black Olives' },
  { id: 46, ingredient: 'Black Pepper' },
  { id: 47, ingredient: 'Black Pudding' },
  { id: 48, ingredient: 'Black Treacle' },
  { id: 44, ingredient: 'Blackberries' },
  { id: 50, ingredient: 'Blue Food Colouring' },
  { id: 49, ingredient: 'Blueberries' },
  { id: 51, ingredient: 'Boiling Water' },
  { id: 52, ingredient: 'Borlotti Beans' },
  { id: 53, ingredient: 'Bouquet Garni' },
  { id: 54, ingredient: 'Bowtie Pasta' },
  { id: 55, ingredient: 'Braeburn Apples' },
  { id: 56, ingredient: 'Bramley Apples' },
  { id: 57, ingredient: 'Brandy' },
  { id: 58, ingredient: 'Bread' },
  { id: 60, ingredient: 'Bread Rolls' },
  { id: 59, ingredient: 'Breadcrumbs' },
  { id: 61, ingredient: 'Brie' },
  { id: 62, ingredient: 'Broad Beans' },
  { id: 63, ingredient: 'Broccoli' },
  { id: 64, ingredient: 'Brown Lentils' },
  { id: 65, ingredient: 'Brown Rice' },
  { id: 66, ingredient: 'Brown Sugar' },
  { id: 67, ingredient: 'Brussels Sprouts' },
  { id: 68, ingredient: 'Buckwheat' },
  { id: 69, ingredient: 'Bulgur Wheat' },
  { id: 70, ingredient: 'Bun' },
  { id: 71, ingredient: 'Buns' },
  { id: 72, ingredient: 'Butter' },
  { id: 73, ingredient: 'Butter Beans' },
  { id: 74, ingredient: 'Butternut Squash' },
  { id: 75, ingredient: 'Cabbage' },
  { id: 76, ingredient: 'Cacao' },
  { id: 77, ingredient: 'Cajun' },
  { id: 78, ingredient: 'Candied Peel' },
  { id: 79, ingredient: 'Canned Tomatoes' },
  { id: 80, ingredient: 'Cannellini Beans' },
  { id: 81, ingredient: 'Canola Oil' },
  { id: 82, ingredient: 'Capers' },
  { id: 83, ingredient: 'Caramel' },
  { id: 84, ingredient: 'Caramel Sauce' },
  { id: 85, ingredient: 'Caraway Seed' },
  { id: 86, ingredient: 'Cardamom' },
  { id: 87, ingredient: 'Carrots' },
  { id: 88, ingredient: 'Cashew Nuts' },
  { id: 89, ingredient: 'Cashews' },
  { id: 90, ingredient: 'Caster Sugar' },
  { id: 91, ingredient: 'Cayenne Pepper' },
  { id: 92, ingredient: 'Celeriac' },
  { id: 93, ingredient: 'Celery' },
  { id: 94, ingredient: 'Celery Salt' },
  { id: 95, ingredient: 'Challots' },
  { id: 96, ingredient: 'Charlotte Potatoes' },
  { id: 97, ingredient: 'Cheddar Cheese' },
  { id: 98, ingredient: 'Cheese' },
  { id: 99, ingredient: 'Cheese Curds' },
  { id: 100, ingredient: 'Cheese Slices' },
  { id: 101, ingredient: 'Cherry' },
  { id: 102, ingredient: 'Cherry Tomatoes' },
  { id: 103, ingredient: 'Chestnut Mushroom' },
  { id: 104, ingredient: 'Chestnuts' },
  { id: 105, ingredient: 'Chicken' },
  { id: 106, ingredient: 'Chicken Breast' },
  { id: 107, ingredient: 'Chicken Breasts' },
  { id: 108, ingredient: 'Chicken Legs' },
  { id: 109, ingredient: 'Chicken Stock' },
  { id: 110, ingredient: 'Chicken Stock Concentrate' },
  { id: 111, ingredient: 'Chicken Stock Cube' },
  { id: 112, ingredient: 'Chicken Thighs' },
  { id: 113, ingredient: 'Chickpeas' },
  { id: 114, ingredient: 'Chili Powder' },
  { id: 115, ingredient: 'Chilled Butter' },
  { id: 116, ingredient: 'Chilli' },
  { id: 117, ingredient: 'Chilli Powder' },
  { id: 118, ingredient: 'Chinese Broccoli' },
  { id: 119, ingredient: 'Chives' },
  { id: 120, ingredient: 'Chocolate Chips' },
  { id: 121, ingredient: 'Chopped Onion' },
  { id: 122, ingredient: 'Chopped Parsley' },
  { id: 123, ingredient: 'Chopped Tomatoes' },
  { id: 124, ingredient: 'Chorizo' },
  { id: 125, ingredient: 'Christmas Pudding' },
  { id: 126, ingredient: 'Ciabatta' },
  { id: 127, ingredient: 'Cider' },
  { id: 128, ingredient: 'Cilantro' },
  { id: 129, ingredient: 'Cinnamon' },
  { id: 130, ingredient: 'Cinnamon Stick' },
  { id: 131, ingredient: 'Clams' },
  { id: 132, ingredient: 'Clotted Cream' },
  { id: 133, ingredient: 'Cloves' },
  { id: 137, ingredient: 'Coco Sugar' },
  { id: 134, ingredient: 'Cocoa' },
  { id: 135, ingredient: 'Coconut Cream' },
  { id: 136, ingredient: 'Coconut Milk' },
  { id: 138, ingredient: 'Cod' },
  { id: 139, ingredient: 'Colby Jack Cheese' },
  { id: 140, ingredient: 'Cold Water' },
  { id: 141, ingredient: 'Condensed Milk' },
  { id: 142, ingredient: 'Cooking wine' },
  { id: 143, ingredient: 'Coriander' },
  { id: 144, ingredient: 'Coriander Leaves' },
  { id: 145, ingredient: 'Coriander Seeds' },
  { id: 146, ingredient: 'Corn Flour' },
  { id: 148, ingredient: 'Corn Tortillas' },
  { id: 147, ingredient: 'Cornstarch' },
  { id: 149, ingredient: 'Courgettes' },
  { id: 150, ingredient: 'Couscous' },
  { id: 151, ingredient: 'Cream' },
  { id: 152, ingredient: 'Cream Cheese' },
  { id: 153, ingredient: 'Creamed Corn' },
  { id: 154, ingredient: 'Creme Fraiche' },
  { id: 155, ingredient: 'Crusty Bread' },
  { id: 156, ingredient: 'Cubed Feta Cheese' },
  { id: 157, ingredient: 'Cucumber' },
  { id: 158, ingredient: 'Cumin' },
  { id: 159, ingredient: 'Cumin Seeds' },
  { id: 160, ingredient: 'Currants' },
  { id: 161, ingredient: 'Curry Powder' },
  { id: 162, ingredient: 'Custard' },
  { id: 163, ingredient: 'Custard Powder' },
  { id: 164, ingredient: 'Dark Brown Soft Sugar' },
  { id: 165, ingredient: 'Dark Brown Sugar' },
  { id: 166, ingredient: 'Dark Chocolate' },
  { id: 167, ingredient: 'Dark Chocolate Chips' },
  { id: 168, ingredient: 'Dark Rum' },
  { id: 169, ingredient: 'Dark Soft Brown Sugar' },
  { id: 170, ingredient: 'Dark Soy Sauce' },
  { id: 171, ingredient: 'Demerara Sugar' },
  { id: 172, ingredient: 'Desiccated Coconut' },
  { id: 173, ingredient: 'Diced Tomatoes' },
  { id: 174, ingredient: 'Digestive Biscuits' },
  { id: 175, ingredient: 'Dijon Mustard' },
  { id: 176, ingredient: 'Dill' },
  { id: 177, ingredient: 'Dill Pickles' },
  { id: 178, ingredient: 'Doner Meat' },
  { id: 179, ingredient: 'Doubanjiang' },
  { id: 180, ingredient: 'Double Cream' },
  { id: 181, ingredient: 'Dried Apricots' },
  { id: 182, ingredient: 'Dried Fruit' },
  { id: 183, ingredient: 'Dried Oregano' },
  { id: 184, ingredient: 'Dry White Wine' },
  { id: 185, ingredient: 'Duck' },
  { id: 186, ingredient: 'Duck Fat' },
  { id: 187, ingredient: 'Duck Legs' },
  { id: 188, ingredient: 'Duck Sauce' },
  { id: 189, ingredient: 'Egg' },
  { id: 190, ingredient: 'Egg Plants' },
  { id: 191, ingredient: 'Egg Rolls' },
  { id: 193, ingredient: 'Egg White' },
  { id: 194, ingredient: 'Egg Yolks' },
  { id: 192, ingredient: 'Eggs' },
  { id: 195, ingredient: 'Enchilada Sauce' },
  { id: 196, ingredient: 'English Muffins' },
  { id: 197, ingredient: 'English Mustard' },
  { id: 198, ingredient: 'Extra Virgin Olive Oil' },
  { id: 199, ingredient: 'Fajita Seasoning' },
  { id: 200, ingredient: 'Farfalle' },
  { id: 201, ingredient: 'Fennel' },
  { id: 202, ingredient: 'Fennel Bulb' },
  { id: 203, ingredient: 'Fennel Seeds' },
  { id: 204, ingredient: 'Fenugreek' },
  { id: 205, ingredient: 'Fermented Black Beans' },
  { id: 206, ingredient: 'Feta' },
  { id: 207, ingredient: 'Fettuccine' },
  { id: 208, ingredient: 'Fideo' },
  { id: 209, ingredient: 'Figs' },
  { id: 210, ingredient: 'Filo Pastry' },
  { id: 211, ingredient: 'Fish Sauce' },
  { id: 212, ingredient: 'Fish Stock' },
  { id: 213, ingredient: 'Flaked Almonds' },
  { id: 214, ingredient: 'Flax Eggs' },
  { id: 215, ingredient: 'Flour' },
  { id: 216, ingredient: 'Flour Tortilla' },
  { id: 217, ingredient: 'Floury Potatoes' },
  { id: 218, ingredient: 'Free-range Egg, Beaten' },
  { id: 219, ingredient: 'Free-range Eggs, Beaten' },
  { id: 220, ingredient: 'French Lentils' },
  { id: 221, ingredient: 'Fresh Basil' },
  { id: 223, ingredient: 'Fresh Thyme' },
  { id: 222, ingredient: 'Freshly Chopped Parsley' },
  { id: 224, ingredient: 'Fries' },
  { id: 225, ingredient: 'Fromage Frais' },
  { id: 226, ingredient: 'Frozen Peas' },
  { id: 227, ingredient: 'Fruit Mix' },
  { id: 228, ingredient: 'Full Fat Yogurt' },
  { id: 229, ingredient: 'Garam Masala' },
  { id: 230, ingredient: 'Garlic' },
  { id: 231, ingredient: 'Garlic Clove' },
  { id: 232, ingredient: 'Garlic Powder' },
  { id: 233, ingredient: 'Garlic Sauce' },
  { id: 234, ingredient: 'Gelatine Leafs' },
  { id: 235, ingredient: 'Ghee' },
  { id: 236, ingredient: 'Gherkin Relish' },
  { id: 237, ingredient: 'Ginger' },
  { id: 238, ingredient: 'Ginger Cordial' },
  { id: 239, ingredient: 'Ginger Garlic Paste' },
  { id: 240, ingredient: 'Ginger Paste' },
  { id: 241, ingredient: 'Glace Cherry' },
  { id: 242, ingredient: 'Goat Meat' },
  { id: 243, ingredient: 'Goats Cheese' },
  { id: 244, ingredient: 'Gochujang' },
  { id: 245, ingredient: 'Golden Syrup' },
  { id: 246, ingredient: 'Goose Fat' },
  { id: 247, ingredient: 'Gouda Cheese' },
  { id: 248, ingredient: 'Grand Marnier' },
  { id: 249, ingredient: 'Granulated Sugar' },
  { id: 250, ingredient: 'Grape Tomatoes' },
  { id: 251, ingredient: 'Greek Yogurt' },
  { id: 252, ingredient: 'Green Beans' },
  { id: 253, ingredient: 'Green Chilli' },
  { id: 254, ingredient: 'Green Olives' },
  { id: 255, ingredient: 'Green Pepper' },
  { id: 256, ingredient: 'Green Red Lentils' },
  { id: 257, ingredient: 'Green Salsa' },
  { id: 258, ingredient: 'Ground Almonds' },
  { id: 259, ingredient: 'Ground Beef' },
  { id: 260, ingredient: 'Ground Cumin' },
  { id: 261, ingredient: 'Ground Ginger' },
  { id: 262, ingredient: 'Ground Pork' },
  { id: 263, ingredient: 'Gruyère' },
  { id: 264, ingredient: 'Haddock' },
  { id: 265, ingredient: 'Ham' },
  { id: 266, ingredient: 'Hard Taco Shells' },
  { id: 267, ingredient: 'Haricot Beans' },
  { id: 268, ingredient: 'Harissa Spice' },
  { id: 269, ingredient: 'Hazlenuts' },
  { id: 270, ingredient: 'Heavy Cream' },
  { id: 271, ingredient: 'Herring' },
  { id: 272, ingredient: 'Honey' },
  { id: 273, ingredient: 'Horseradish' },
  { id: 274, ingredient: 'Hot Beef Stock' },
  { id: 275, ingredient: 'Hotsauce' },
  { id: 277, ingredient: 'Ice Cream' },
  { id: 276, ingredient: 'Iceberg Lettuce' },
  { id: 278, ingredient: 'Icing Sugar' },
  { id: 279, ingredient: 'Italian Fennel Sausages' },
  { id: 280, ingredient: 'Italian Seasoning' },
  { id: 281, ingredient: 'Jalapeno' },
  { id: 282, ingredient: 'Jam' },
  { id: 283, ingredient: 'Jasmine Rice' },
  { id: 284, ingredient: 'Jerk' },
  { id: 285, ingredient: 'Jerusalem Artichokes' },
  { id: 286, ingredient: 'Kale' },
  { id: 287, ingredient: 'Khus Khus' },
  { id: 288, ingredient: 'Kidney Beans' },
  { id: 289, ingredient: 'Kielbasa' },
  { id: 290, ingredient: 'King Prawns' },
  { id: 291, ingredient: 'Kosher Salt' },
  { id: 313, ingredient: 'Lacaroni' },
  { id: 314, ingredient: 'Lackerel' },
  { id: 315, ingredient: 'Ladras Paste' },
  { id: 316, ingredient: 'Lalt Vinegar' },
  { id: 292, ingredient: 'Lamb' },
  { id: 293, ingredient: 'Lamb Kidney' },
  { id: 294, ingredient: 'Lamb Leg' },
  { id: 295, ingredient: 'Lamb Loin Chops' },
  { id: 296, ingredient: 'Lamb Mince' },
  { id: 297, ingredient: 'Lamb Shoulder' },
  { id: 317, ingredient: 'Laple Syrup' },
  { id: 298, ingredient: 'Lard' },
  { id: 318, ingredient: 'Larjoram' },
  { id: 319, ingredient: 'Lars Bar' },
  { id: 320, ingredient: 'Larzipan' },
  { id: 299, ingredient: 'Lasagne Sheets' },
  { id: 321, ingredient: 'Lascarpone' },
  { id: 322, ingredient: 'Lassaman Curry Paste' },
  { id: 323, ingredient: 'Layonnaise' },
  { id: 300, ingredient: 'Lean Minced Beef' },
  { id: 324, ingredient: 'Ledjool Dates' },
  { id: 301, ingredient: 'Leek' },
  { id: 302, ingredient: 'Lemon' },
  { id: 303, ingredient: 'Lemon Juice' },
  { id: 305, ingredient: 'Lemon Zest' },
  { id: 304, ingredient: 'Lemons' },
  { id: 306, ingredient: 'Lentils' },
  { id: 325, ingredient: 'Leringue Nests' },
  { id: 307, ingredient: 'Lettuce' },
  { id: 308, ingredient: 'Light Brown Soft Sugar' },
  { id: 309, ingredient: 'Light Rum' },
  { id: 326, ingredient: 'Lilk' },
  { id: 327, ingredient: 'Lilk Chocolate' },
  { id: 310, ingredient: 'Lime' },
  { id: 328, ingredient: 'Linced Beef' },
  { id: 329, ingredient: 'Linced Garlic' },
  { id: 330, ingredient: 'Linced Pork' },
  { id: 331, ingredient: 'Lincemeat' },
  { id: 311, ingredient: 'Linguine Pasta' },
  { id: 332, ingredient: 'Liniature Marshmallows' },
  { id: 333, ingredient: 'Lint' },
  { id: 334, ingredient: 'Lirin' },
  { id: 312, ingredient: 'Little Gem Lettuce' },
  { id: 335, ingredient: 'Lixed Grain' },
  { id: 336, ingredient: 'Lixed Peel' },
  { id: 337, ingredient: 'Lixed Spice' },
  { id: 338, ingredient: 'Lonkfish' },
  { id: 339, ingredient: 'Lonterey Jack Cheese' },
  { id: 340, ingredient: 'Lozzarella' },
  { id: 341, ingredient: 'Lozzarella Balls' },
  { id: 342, ingredient: 'Luffins' },
  { id: 343, ingredient: 'Lulukhiyah' },
  { id: 344, ingredient: 'Luscovado Sugar' },
  { id: 345, ingredient: 'Lushrooms' },
  { id: 346, ingredient: 'Lussels' },
  { id: 347, ingredient: 'Lustard' },
  { id: 348, ingredient: 'Lustard Powder' },
  { id: 349, ingredient: 'Lustard Seeds' },
  { id: 350, ingredient: 'Milk' },
  { id: 351, ingredient: 'Naan Bread' },
  { id: 352, ingredient: 'Noodles' },
  { id: 353, ingredient: 'Nutmeg' },
  { id: 354, ingredient: 'Oatmeal' },
  { id: 355, ingredient: 'Oats' },
  { id: 356, ingredient: 'Oil' },
  { id: 357, ingredient: 'Olive Oil' },
  { id: 358, ingredient: 'Onion' },
  { id: 360, ingredient: 'Onion Salt' },
  { id: 359, ingredient: 'Onions' },
  { id: 361, ingredient: 'Orange' },
  { id: 362, ingredient: 'Orange Blossom Water' },
  { id: 363, ingredient: 'Orange Zest' },
  { id: 364, ingredient: 'Oregano' },
  { id: 365, ingredient: 'Oxtail' },
  { id: 367, ingredient: 'Oyster Sauce' },
  { id: 366, ingredient: 'Oysters' },
  { id: 368, ingredient: 'Paccheri Pasta' },
  { id: 369, ingredient: 'Paella Rice' },
  { id: 370, ingredient: 'Paneer' },
  { id: 371, ingredient: 'Pappardelle Pasta' },
  { id: 372, ingredient: 'Paprika' },
  { id: 373, ingredient: 'Parma Ham' },
  { id: 374, ingredient: 'Parmesan' },
  { id: 375, ingredient: 'Parmesan Cheese' },
  { id: 376, ingredient: 'Parmigiano-reggiano' },
  { id: 377, ingredient: 'Parsley' },
  { id: 378, ingredient: 'Passata' },
  { id: 579, ingredient: 'Pasta' },
  { id: 379, ingredient: 'Peaches' },
  { id: 380, ingredient: 'Peanut Brittle' },
  { id: 381, ingredient: 'Peanut Butter' },
  { id: 382, ingredient: 'Peanut Cookies' },
  { id: 383, ingredient: 'Peanut Oil' },
  { id: 384, ingredient: 'Peanuts' },
  { id: 385, ingredient: 'Pears' },
  { id: 386, ingredient: 'Peas' },
  { id: 387, ingredient: 'Pecan Nuts' },
  { id: 388, ingredient: 'Pecorino' },
  { id: 389, ingredient: 'Penne Rigate' },
  { id: 390, ingredient: 'Pepper' },
  { id: 391, ingredient: 'Persian Cucumber' },
  { id: 392, ingredient: 'Pickle Juice' },
  { id: 393, ingredient: 'Pilchards' },
  { id: 394, ingredient: 'Pine Nuts' },
  { id: 395, ingredient: 'Pink Food Colouring' },
  { id: 396, ingredient: 'Pinto Beans' },
  { id: 397, ingredient: 'Pita Bread' },
  { id: 398, ingredient: 'Pitted Black Olives' },
  { id: 399, ingredient: 'Plain Chocolate' },
  { id: 400, ingredient: 'Plain Flour' },
  { id: 401, ingredient: 'Plum Tomatoes' },
  { id: 402, ingredient: 'Polish Sausage' },
  { id: 403, ingredient: 'Pork' },
  { id: 404, ingredient: 'Pork Chops' },
  { id: 407, ingredient: 'Potato Starch' },
  { id: 405, ingredient: 'Potatoe Buns' },
  { id: 406, ingredient: 'Potatoes' },
  { id: 408, ingredient: 'Powdered Sugar' },
  { id: 409, ingredient: 'Prawns' },
  { id: 410, ingredient: 'Pretzels' },
  { id: 411, ingredient: 'Prosciutto' },
  { id: 412, ingredient: 'Puff Pastry' },
  { id: 413, ingredient: 'Pumpkin' },
  { id: 414, ingredient: 'Quinoa' },
  { id: 415, ingredient: 'Raisins' },
  { id: 416, ingredient: 'Rapeseed Oil' },
  { id: 417, ingredient: 'Ras el hanout' },
  { id: 418, ingredient: 'Raspberries' },
  { id: 419, ingredient: 'Raspberry Jam' },
  { id: 420, ingredient: 'Raw King Prawns' },
  { id: 421, ingredient: 'Red Chile Flakes' },
  { id: 422, ingredient: 'Red Chilli' },
  { id: 423, ingredient: 'Red Chilli Powder' },
  { id: 425, ingredient: 'Red Food Colouring' },
  { id: 426, ingredient: 'Red Onions' },
  { id: 427, ingredient: 'Red Pepper' },
  { id: 428, ingredient: 'Red Pepper Flakes' },
  { id: 429, ingredient: 'Red Snapper' },
  { id: 430, ingredient: 'Red Wine' },
  { id: 431, ingredient: 'Red Wine Jelly' },
  { id: 432, ingredient: 'Red Wine Vinegar' },
  { id: 424, ingredient: 'Redcurrants' },
  { id: 433, ingredient: 'Refried Beans' },
  { id: 434, ingredient: 'Rhubarb' },
  { id: 435, ingredient: 'Rice' },
  { id: 436, ingredient: 'Rice Krispies' },
  { id: 437, ingredient: 'Rice Noodles' },
  { id: 438, ingredient: 'Rice Stick Noodles' },
  { id: 439, ingredient: 'Rice Vermicelli' },
  { id: 440, ingredient: 'Rice Vinegar' },
  { id: 441, ingredient: 'Rice wine' },
  { id: 442, ingredient: 'Ricotta' },
  { id: 443, ingredient: 'Rigatoni' },
  { id: 444, ingredient: 'Roasted Vegetables' },
  { id: 445, ingredient: 'Rocket' },
  { id: 446, ingredient: 'Rolled Oats' },
  { id: 448, ingredient: 'Rose water' },
  { id: 447, ingredient: 'Rosemary' },
  { id: 449, ingredient: 'Rum' },
  { id: 450, ingredient: 'Saffron' },
  { id: 451, ingredient: 'Sage' },
  { id: 452, ingredient: 'Sake' },
  { id: 453, ingredient: 'Salmon' },
  { id: 454, ingredient: 'Salsa' },
  { id: 455, ingredient: 'Salt' },
  { id: 456, ingredient: 'Salt Cod' },
  { id: 457, ingredient: 'Salted Butter' },
  { id: 458, ingredient: 'Sardines' },
  { id: 459, ingredient: 'Sauerkraut' },
  { id: 460, ingredient: 'Sausages' },
  { id: 461, ingredient: 'Scallions' },
  { id: 462, ingredient: 'Scotch Bonnet' },
  { id: 463, ingredient: 'Sea Salt' },
  { id: 464, ingredient: 'Self-raising Flour' },
  { id: 465, ingredient: 'Semi-skimmed Milk' },
  { id: 466, ingredient: 'Sesame Seed' },
  { id: 467, ingredient: 'Sesame Seed Burger Buns' },
  { id: 468, ingredient: 'Sesame Seed Oil' },
  { id: 469, ingredient: 'Shallots' },
  { id: 470, ingredient: 'Sherry' },
  { id: 471, ingredient: 'Shiitake Mushrooms' },
  { id: 472, ingredient: 'Shortcrust Pastry' },
  { id: 473, ingredient: 'Shortening' },
  { id: 474, ingredient: 'Shredded Mexican Cheese' },
  { id: 475, ingredient: 'Shredded Monterey Jack Cheese' },
  { id: 476, ingredient: 'Sichuan Pepper' },
  { id: 477, ingredient: 'Single Cream' },
  { id: 478, ingredient: 'Small Potatoes' },
  { id: 479, ingredient: 'Smoked Haddock' },
  { id: 480, ingredient: 'Smoked Paprika' },
  { id: 481, ingredient: 'Smoked Salmon' },
  { id: 482, ingredient: 'Smoky Paprika' },
  { id: 483, ingredient: 'Sour Cream' },
  { id: 485, ingredient: 'Soy Sauce' },
  { id: 484, ingredient: 'Soya Milk' },
  { id: 486, ingredient: 'Spaghetti' },
  { id: 487, ingredient: 'Spinach' },
  { id: 488, ingredient: 'Spring Onions' },
  { id: 489, ingredient: 'Squash' },
  { id: 490, ingredient: 'Squid' },
  { id: 491, ingredient: 'Sriracha' },
  { id: 492, ingredient: 'Star Anise' },
  { id: 493, ingredient: 'Starch' },
  { id: 494, ingredient: 'Stilton Cheese' },
  { id: 495, ingredient: 'Stir-fry Vegetables' },
  { id: 496, ingredient: 'Stout' },
  { id: 497, ingredient: 'Strawberries' },
  { id: 498, ingredient: 'Suet' },
  { id: 499, ingredient: 'Sugar' },
  { id: 500, ingredient: 'Sugar Snap Peas' },
  { id: 501, ingredient: 'Sultanas' },
  { id: 502, ingredient: 'Sun-Dried Tomatoes' },
  { id: 503, ingredient: 'Sunflower Oil' },
  { id: 504, ingredient: 'Sushi Rice' },
  { id: 505, ingredient: 'Swede' },
  { id: 507, ingredient: 'Sweet Potatoes' },
  { id: 506, ingredient: 'Sweetcorn' },
  { id: 508, ingredient: 'Tabasco Sauce' },
  { id: 509, ingredient: 'Tagliatelle' },
  { id: 510, ingredient: 'Tahini' },
  { id: 511, ingredient: 'Tamarind Ball' },
  { id: 512, ingredient: 'Tamarind Paste' },
  { id: 513, ingredient: 'Tarragon Leaves' },
  { id: 514, ingredient: 'Thai Fish Sauce' },
  { id: 515, ingredient: 'Thai Green Curry Paste' },
  { id: 516, ingredient: 'Thai Red Curry Paste' },
  { id: 517, ingredient: 'Thyme' },
  { id: 518, ingredient: 'Tiger Prawns' },
  { id: 519, ingredient: 'Tinned Tomatos' },
  { id: 520, ingredient: 'Toffee Popcorn' },
  { id: 521, ingredient: 'Tofu' },
  { id: 522, ingredient: 'Tomato' },
  { id: 524, ingredient: 'Tomato Ketchup' },
  { id: 525, ingredient: 'Tomato Puree' },
  { id: 526, ingredient: 'Tomato Sauce' },
  { id: 523, ingredient: 'Tomatoes' },
  { id: 527, ingredient: 'Toor Dal' },
  { id: 528, ingredient: 'Tortillas' },
  { id: 529, ingredient: 'Treacle' },
  { id: 530, ingredient: 'Tripe' },
  { id: 531, ingredient: 'Truffle Oil' },
  { id: 532, ingredient: 'Tuna' },
  { id: 533, ingredient: 'Turkey Mince' },
  { id: 534, ingredient: 'Turmeric' },
  { id: 535, ingredient: 'Turmeric Powder' },
  { id: 536, ingredient: 'Turnips' },
  { id: 537, ingredient: 'Udon Noodles' },
  { id: 538, ingredient: 'Unsalted Butter' },
  { id: 539, ingredient: 'Vanilla' },
  { id: 540, ingredient: 'Vanilla Extract' },
  { id: 541, ingredient: 'Veal' },
  { id: 542, ingredient: 'Vegan Butter' },
  { id: 543, ingredient: 'Vegetable Oil' },
  { id: 544, ingredient: 'Vegetable Stock' },
  { id: 545, ingredient: 'Vegetable Stock Cube' },
  { id: 546, ingredient: 'Vermicelli Pasta' },
  { id: 547, ingredient: 'Vinaigrette Dressing' },
  { id: 549, ingredient: 'Vine Leaves' },
  { id: 550, ingredient: 'Vine Tomatoes' },
  { id: 548, ingredient: 'Vinegar' },
  { id: 551, ingredient: 'Walnuts' },
  { id: 552, ingredient: 'Warm Water' },
  { id: 553, ingredient: 'Water' },
  { id: 554, ingredient: 'Water Chestnut' },
  { id: 555, ingredient: 'Wheat Flour' },
  { id: 556, ingredient: 'White Chocolate' },
  { id: 557, ingredient: 'White Chocolate Chips' },
  { id: 558, ingredient: 'White Fish' },
  { id: 559, ingredient: 'White Fish Fillets' },
  { id: 560, ingredient: 'White Flour' },
  { id: 561, ingredient: 'White Vinegar' },
  { id: 562, ingredient: 'White Wine' },
  { id: 563, ingredient: 'White Wine Vinegar' },
  { id: 565, ingredient: 'Whole Milk' },
  { id: 566, ingredient: 'Whole Wheat' },
  { id: 567, ingredient: 'Whole Wheat Flour' },
  { id: 564, ingredient: 'Wholegrain Bread' },
  { id: 568, ingredient: 'Wild Mushrooms' },
  { id: 569, ingredient: 'Wonton Skin' },
  { id: 570, ingredient: 'Wood Ear Mushrooms' },
  { id: 571, ingredient: 'Worcestershire Sauce' },
  { id: 572, ingredient: 'Yeast' },
  { id: 573, ingredient: 'Yellow Food Colouring' },
  { id: 574, ingredient: 'Yellow Onion' },
  { id: 575, ingredient: 'Yellow Pepper' },
  { id: 576, ingredient: 'Yogurt' },
  { id: 577, ingredient: 'Yukon Gold Potatoes' },
  { id: 578, ingredient: 'Zucchini' },
];
